export const FETCH_SCRAPED_DATA = {
  FETCH_ALL_SCRAPED_BLOGS: 'FETCH_ALL_SCRAPED_BLOGS',
  FETCH_ALL_SCRAPED_RELATED_TERMS: 'FETCH_ALL_SCRAPED_RELATED_TERMS',
  FETCH_ALL_SCRAPED_POPULAR_TERM_IMAGES:
    'FETCH_ALL_SCRAPED_POPULAR_TERM_IMAGES',
  FETCH_ALL_SCRAPED_POPULAR_KEYWORDS_DETAILED_DATA:
    'FETCH_ALL_SCRAPED_POPULAR_KEYWORDS_DETAILED_DATA',
  FETCH_ALL_SCRAPED_POPULAR_KEYWORDS_DETAILED_DATA_BY_BLOG_URL:
    'FETCH_ALL_SCRAPED_POPULAR_KEYWORDS_DETAILED_DATA_BY_BLOG_URL',
  FETCH_ALL_SCRAPED_BLOG_CLASS: 'FETCH_ALL_SCRAPED_BLOG_CLASS',
  FETCH_ALL_SCRAPED_DUPLICATED_BLOGS: 'FETCH_ALL_SCRAPED_DUPLICATED_BLOGS',
  FETCH_ALL_SCRAPED_BLOG_KEYWORDS_ANALYSIS:
    'FETCH_ALL_SCRAPED_BLOG_KEYWORDS_ANALYSIS',
  FETCH_ALL_SCRAPED_BLOG_SHUFFLED_DATA: 'FETCH_ALL_SCRAPED_BLOG_SHUFFLED_DATA',
  FETCH_ALL_SUGGESTED_BLOGS_FROM_KEYWORD:
    'FETCH_ALL_SUGGESTED_BLOGS_FROM_KEYWORD',
  FETCH_ALL_MANUSCRIPT_ANALYSIS_PAGE_DATA:
    'FETCH_ALL_MANUSCRIPT_ANALYSIS_PAGE_DATA',
  FETCH_ALL_BLOG_SECTIONS_INFORMATION: 'FETCH_ALL_BLOG_SECTIONS_INFORMATIONS',
  FETCH_ALL_BLOG_SEARCH_VOLUME_DATA: 'FETCH_ALL_BLOG_SEARCH_VOLUME_DATA',
};
