export const APP_IMAGES = {
  influencer: '/images/ico_influencer.png',
  blogClose: '/images/ico_blog_close.png',
  blogNext: '/images/ico_blog_next.png',
  blogPrev: '/images/ico_blog_prev.png',
  blogWindow: '/images/ico_blog_window.png',
  keywordSample1: '/images/keyword_sample1.jpg',
  keywordSample2: '/images/keyword_sample2.jpg',
  keywordSample3: '/images/keyword_sample3.jpg',
  keywordSample4: '/images/keyword_sample4.jpg',
  keywordSample5: '/images/keyword_sample5.jpg',
  keywordSample6: '/images/keyword_sample6.jpg',
  keywordSample7: '/images/keyword_sample7.jpg',
  keywordSample8: '/images/keyword_sample8.jpg',
  keywordSample9: '/images/keyword_sample9.jpg',
  noImage: '/images/ico_noimg.png',
  keywordView1: '/images/keyword_view1.jpg',
  keywordView2: '/images/keyword_view2.jpg',
  keywordView3: '/images/keyword_view3.jpg',
  keywordView4: '/images/keyword_view4.jpg',
  keywordView5: '/images/keyword_view5.jpg',
  keywordView6: '/images/keyword_view6.jpg',
  keywordView7: '/images/keyword_view7.jpg',
  keywordView8: '/images/keyword_view8.jpg',
  hashtagIcon: '/images/ico_hashtag.png',
};
